### ISSUE TITLE
Does this need SpringFramework?

### ISSUE THREAD

**Issue by fillefilip8** [Qkyrie/Twitch#3]

**Comment by Qkyrie** [comment]
Hi

The core application does not rely on being in a Spring Environment, however, it does rely on some packages/utility classes spring provides, mainly for checking state / Rest Template. You're one of quite some people asking this question and therefore my question to you: Is there a problem using some Spring dependencies? I'm considering changing the actual implementation to remove those packages if people have valid use cases.
